#!/bin/bash

# Read the previous version from package.json
oldVersion=`node -p "require('./package.json').version"`

# Prompt version bump level
echo "Give new version (previous $oldVersion):"
read newVersion

# Change version in package.json and commit the change
echo "Changing version in package.json..."
node -p "var pkg = require('./package.json'); pkg.version='$newVersion'; JSON.stringify(pkg, null, 2)" > tmp.json
mv tmp.json package.json

# Commit the version change and tag it
echo "Commiting and tagging changes..."
git add package.json
git commit --quiet -m "Version $newVersion"
git tag v$newVersion

# Push main and tags
echo "Pushing changes to origin..."
git push --quiet origin main
git push --quiet origin --tags

# Checkout production, pull and merge main to it
echo "Merging changes to production..."
git checkout --quiet production
git pull --quiet 
git merge --quiet main

# Push production and return to main
echo "Pushing changes to production..."
git push --quiet origin production
git checkout --quiet main

echo "DONE!"
